---
- name: Install jenkins
  host: jenkins_master 
  become: yes
  become_user: root

  tasks:                         # ansible.builtin.apt module: for Managing apt-packages
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Download jenkins key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key     #from jenkin long-term support installation command
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins.list

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: install fontconfig
  shell: apt install fontconfig -y

- name: install java
  shell: apt install fontconfig openjdk-17-jre -y

- name: Install jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Start jenkins service
  ansible.builtin.apt:
    name: jenkins
    state: started
    enabled: yes







